@c {-*- Dictionary: /afs/cs/project/clisp/docs/hem/hem; Mode: spell; Package: Hemlock -*-}

@node The Hemlock Netnews Interface
@chapter The Hemlock Netnews Interface
@node Introduction to Netnews in Hemlock, Setting Up Netnews, The Hemlock Netnews Interface, The Hemlock Netnews Interface
@section Introduction to Netnews in Hemlock


@hemlock{} provides a facility for reading bulletin boards through the
NetNews Transfer Protocol (NNTP).  You can easily read Netnews, reply to
news posts, post messages, etc.  The news reading interface is consistent
with that of the @hemlock{} mailer, and most Netnews commands function in the
same manner as their mailer counterparts.

Netnews can be read in one of two different modes.  The first mode, invoked
by the @hid{Netnews} command, allows the user to read new messages in
groups which the user has specified.  This method of reading netnews will
track the highest numbered message in each newsgroup and only show new
messages which have arrived since then.  The @hid{Netnews Browse} command
invokes the other method of reading netnews.  This mode displays a list of
all newsgroups, and the user may choose to read messages in any of them.
By default, the news reader will not track the latest message read when
browsing, and it will always display the last few messages.


@node Setting Up Netnews, Starting Netnews, Introduction to Netnews in Hemlock, The Hemlock Netnews Interface
@section Setting Up Netnews

To start reading bulletin boards from @hemlock{} you probably need to create a
file containing the newsgroups you want to read.

@defvr {Hemlock Variable} {Netnews Group File} @val{".hemlock-groups"}
   When you invoke the @hid{Netnews} command, @hemlock{} merges the value of
   this variable with your home directory and looks there for a list of
   groups (one per line) to read.
@end defvr

@defvr {Hemlock Variable} {Netnews Database File} @val{".hemlock-netnews"}
When you invoke the @hid{Netnews} command, @hemlock{} merges the value of
this variable with your home directory.  This file maintains a pointer to
the highest numbered message read in each group in @hid{Netnews Group
File}.
@end defvr

@deffn {Command} {List All Groups}
   When you invoke this command, @hemlock{} creates a buffer called
   @hid{Netnews Groups} and inserts the names of all accessible Netnews
   groups into it alphabetically.  You may find this useful if you choose to set
   up your @hid{Netnews Group File} manually.
@end deffn

@defvr {Hemlock Variable} {Netnews NNTP Server} @val{"netnews.srv.cs.cmu.edu"}
This variable stores the host name of the machine which @hemlock{} will use
as the NNTP server.
@end defvr

@defvr {Hemlock Variable} {Netnews NNTP Timeout Period} @val{30}
This is the number of seconds @hemlock{} will wait trying to connect to the
NNTP server.  If a connection is not made within this time period, the
connection will time out and an error will be signalled.
@end defvr

@menu
* News-Browse Mode::
@end menu

@node News-Browse Mode,  , Setting Up Netnews, Setting Up Netnews
@subsection News-Browse Mode

   @hid{News-Browse} mode provides an easy method of adding groups to
   your @hid{Netnews Group File}.

@deffn {Command} {Netnews Browse}
   This command sets up a buffer in @hid{News-Browse} mode with all
   available groups listed one per line.  Groups may be read or added
   to your group file using various commands in this mode.
@end deffn

@deffn {Command} {Netnews Browse Add Group To File} stuff (bound to @b{a} in @hid{News-Browse} mode)
@deffnx {Command} {Netnews Browse Pointer Add Group to File}
@hid{Netnews Browse Add Group to File} adds the group under the point to
your group file, and @hid{Netnews Browse Pointer Add Group To File} adds
the group under the mouse pointer without moving the point.
@end deffn

@deffn {Command} {Netnews Browse Read Group} stuff (bound to @b{space} in @hid{News-Browse} mode)
@deffnx {Command} {Netnews Browse Pointer Read Group}
@hid{Netnews Browse Read Group} and @hid{Netnews Browse Pointer Read Group}
read the group under the cursor and the group under the mouse pointer,
respectively.  These commands neither use nor modify the contents of your
@hid{Netnews Database File}; they will always present the last few messages
in the newsgroup, regardless of the last message read.  @hid{Netnews Browse
Pointer Read Group} does not modify the position of the point.
@end deffn

@deffn {Command} {Netnews Quit Browse}
   This command exits @hid{News-Browse} mode.
@end deffn

The @hid{Next Line} and @hid{Previous Line} commands are conveniently bound to
@b{n} and @b{p} in this mode.

@node Starting Netnews, Reading Newnews Messages, Setting Up Netnews, The Hemlock Netnews Interface
@section Starting Netnews

Once your @hid{Netnews Group File} is set up, you may begin reading netnews.

@deffn {Command} {Netnews}
   This command is the main entry point for reading bulletin boards in
   @hemlock{}.  Without an argument, the system looks for what bulletin boards to
   read in the value of @hid{Netnews Group File} and reads each of them in
   succession.  @hemlock{} keeps a pointer to the last message you read in each
   of these groups in your @hid{Netnews Database File}.  Bulletin boards may
   be added to your @hid{Netnews Group File} manually or by using
   the @hid{Netnews Browse} facility.  With an argument, @hemlock{} prompts the 
   user for the name of a bulletin board and reads it.
@end deffn

@deffn {Command} {Netnews Look at Group}
   This command prompts for a group and reads it, ignoring the information
   in your @hid{Netnews Database File}.
@end deffn

When you read a group, @hemlock{} creates a buffer that contains important
header information for the messages in that group.  There are four fields
in each header, one each for the @i{date}, @i{lines}, @i{from}, and
@i{subject}.  The @i{date} field shows when the message was sent, the
@i{lines} field displays how long the message is in lines, the @i{from}
field shows who sent the message, and the @i{subject} field displays the
subject of this message.  If a field for a message is not available, @b{NA}
will appear instead.  You may alter the length of each of these fields by
modifying the following @hemlock{} variables:

@defvr {Hemlock Variable} {Netnews Before Date Field Pad} @val{1}
   How many spaces should be inserted before the date in @hid{News-Headers}
   buffers.
@end defvr

@defvr {Hemlock Variable} {Netnews Date Field Length} @val{6}
@defvrx {Hemlock Variable} {Netnews Line Field Length} @val{3}
@defvrx {Hemlock Variable} {Netnews From Field Length} @val{20}
@defvrx {Hemlock Variable} {Netnews Subject Field Length} @val{43}
   These variables control how long the @i{date}, @i{line}, @i{from}, and
   @i{subject} fields should be in @hid{News-Headers} buffers.
@end defvr

@defvr {Hemlock Variable} {Netnews Field Padding} @val{2}        
   How many spaces should be left between the Netnews @i{date}, @i{from}, 
   @i{lines}, and @i{subject} fields after padding to the required length.
@end defvr

For increased speed, @hemlock{} only inserts headers for a subset of the
messages in each group.  If you have never read a certain group, and the
value of @hid{Netnews New Group Style} is @b{:from-end} (the default),
@hemlock{} inserts some number of the last messages in the group, determined
by the value of @hid{Netnews Batch Count}.  If the value of @hid{Netnews
New Group Style} is @b{:from-start}, @hemlock{} will insert the first batch
of messages in the group.  If you have read a group before, @hemlock{} will
insert the batch of messages following the highest numbered message that
you had read previously.

@defvr {Hemlock Variable} {Netnews Start Over Threshold} @val{350}
   If the number of new messages in a group exceeds the value of this
   variable and @hid{Netnews New Group Style} is @b{:from-end}, @hemlock{} asks
   if you would like to start reading this group from the end.
@end defvr

You may at any time go beyond the messages that are visible using the 
@hid{Netnews Next Line}, @hid{Netnews Previous Line},
@hid{Netnews Headers Scroll Window Up}, and
@hid{Netnews Headers Scroll Down} commands in @hid{News-Headers} mode,
or the @hid{Netnews Next Article} and @hid{Netnews Previous Article}
commands in @hid{News-Message} mode.

@defvr {Hemlock Variable} {Netnews Fetch All Headers} @val{nil}
This variable determines whether Netnews will fetch all headers immediately
upon entering a new group.
@end defvr

@defvr {Hemlock Variable} {Netnews Batch Count} @val{50}
   This variable determines how many headers the Netnews facility will fetch
   at a time.
@end defvr

@defvr {Hemlock Variable} {Netnews New Group Style} @val{:from-end}
This variable determines what happens when you read a group that you have
never read before.  When it is @b{:from-start}, the @hid{Netnews} command
will read from the beginning of a new group forward.  When it is @b{:from-end},
the default, @hid{Netnews} will read the group from the end backward.
@end defvr

@node Reading Newnews Messages, Replying to Messages, Starting Netnews, The Hemlock Netnews Interface
@section Reading Messages

From a @hid{News-Headers} buffer, you may read messages, reply to messages
via the @hemlock{} mailer, or reply to messages via post.  Some commands are
also bound to ease getting from one header to another.

@deffn {Command} {Netnews Show Article} stuff (bound to @b{space} in @hid{News-Headers} mode)
@deffnx {Hemlock Variable} {Netnews Read Style} @val{:multiple}
@deffnx {Hemlock Variable} {Netnews Headers Proportion} @val{0.25}
This command puts the body of the message header under the current point
into a @hid{News-Message} buffer.  If the value of @hid{Netnews Read
Style} is @b{:single}, @hemlock{} changes to the @hid{News-Message}
buffer.  If it is @b{:multiple}, then @hemlock{} splits the current window
into two windows, one for headers and one for message bodies.  The headers
window takes up a proportion of the current window based on the value of
@hid{Netnews Headers Proportion}.  If the window displaying the
@hid{News-Headers} buffer has already been split, and the message
currently displayed in the @hid{News-Message} window is the same as the
one under the current point, this command behaves just like @hid{Netnews
Message Scroll Down}.
@end deffn

@defvr {Hemlock Variable} {Netnews Message Header Fields} @val{nil}
   When this variable is @nil, all available fields are displayed in the
   header of a message.  Otherwise, this variable should containt a list of
   fields to include in message headers.  If an element of this
   list is an atom, then it should be the string name of a field.  If it is
   a cons, then the car should be the string name of a field, and the cdr
   should be the length to which this field should be limited.  Any string
   name is acceptable, and fields that do not exist are ignored.
@end defvr

@deffn {Command} {Netnews Show Whole Header} stuff (bound to @b{w} in @hid{News-Headers} and @hid{News-Message} modes.)
This command displays the entire header for the message currently being
read.  This is to undo the effects of @hid{Netnews Message Header Fields}
for the current message.
@end deffn

@deffn {Command} {Netnews Next Line} stuff (bound to @b{C-n} and @b{Downarrow} in @hid{News-Headers} mode)
@deffnx {Hemlock Variable} {Netnews Last Header Style} @val{:next-headers}
This command moves the current point to the next line.  If you are on the
last visible message, and there are more in the current group, headers for
these messages will be inserted.  If you are on the last header and there
are no more messages in this group, then @hemlock{} will take some action
based on the value of @hid{Netnews Last Header Style}.  If the value of
this variable is @b{:feep}, @hemlock{} feeps you indicating there are no
more messages.  If the value is @b{:next-headers}, @hemlock{} reads in the
headers for the next group in your @hid{Netnews Group File}.  If the value
is @b{:next-article}, @hemlock{} goes on to the next group and shows you
the first unread message.
@end deffn
					 
@deffn {Command} {Netnews Previous Line} stuff (bound to @b{C-p} and @b{Uparrow} in @hid{News-Headers} mode)
This command moves the current point to the previous line.  If you are on
the first visible header, and there are more previous messages, @hemlock{}
inserts the headers for these messages.
@end deffn

@deffn {Command} {Netnews Headers Scroll Window Down} stuff (bound to @b{C-v} in @hid{News-Headers} mode)
@deffnx {Command} {Netnews Headers Scroll Window Up} stuff (bound to @b{M-v} in @hid{News-Headers} mode)
   These commands scroll the headers window up or down one screenfull.  If the
   end of the buffer is visible, @hemlock{} inserts the next batch of headers.
@end deffn

@deffn {Command} {Netnews Next Article} stuff (bound to @b{n} in @hid{News-Message} and @hid{News-Headers} modes)
@deffnx {Command} {Netnews Previous Article} stuff (bound to @b{p} in @hid{News-Message} and @hid{News-Headers} modes)
   These commands insert the next or previous message into a message buffer.
@end deffn

@deffn {Command} {Netnews Message Scroll Down} stuff (bound to @b{space} in @hid{News-Message} mode)
@deffnx {Hemlock Variable} {Netnews Scroll Show Next Message} @val{t}
If the end of the current message is visible, @hemlock{} feeps the user if
the value of @hid{Netnews Scroll Show Next Message} is non-@nil, or it
inserts the next message into this message buffer if that variable is @nil.
If the end of the message is not visible, then @hemlock{} shows the next
screenfull of the current message.
@end deffn

@deffn {Command} {Netnews Message Quit} stuff (bound to @b{q} in @hid{News-Message} mode)
   This command deletes the current message buffer and makes the associated
   @hid{News-Headers} buffer current.
@end deffn
 
@deffn {Command} {Netnews Goto Headers Buffer} stuff (bound to @b{H-h} in @hid{News-Message} mode)
   This command, when invoked from a @hid{News-Message} buffer with an
   associated @hid{News-Headers} buffer, places the associated 
   @hid{News-Headers} buffer into the current window.
@end deffn

@deffn {Command} {Netnews Message Keep Buffer} stuff (bound to @b{k} in @hid{News-Message} mode)
   By default, @hemlock{} uses one buffer to display all messages in a group,
   one at a time.  This command tells @hemlock{} to keep the current message
   buffer intact and start reading messages in another buffer.
@end deffn

@deffn {Command} {Netnews Select Message Buffer} stuff (bound to @b{H-m} in @hid{News-Headers} and @hid{Post} modes.)
   In @hid{News-Headers} mode, this command selects the buffer
   containing the last message read.  In @hid{Post} mode, it selects the
   associated @hid{News-Message} buffer, if there is one.
@end deffn

@deffn {Command} {Netnews Append to File} stuff (bound to @b{a} in @hid{News-Headers} and @hid{News-Message} modes.)
@deffnx {Hemlock Variable} {Netnews Message File} @val{"netnews-messages.txt"}
This command prompts for a file which the current message will be appended
to.  The default file is the value of @hid{Netnews Message File} merged
with your home directory.
@end deffn

@deffn {Command} {Netnews Headers File Message} stuff (bound to @b{o} in @hid{News-Headers} mode)
This command prompts for a mail folder and files the message under the
point into it.  If the folder does not exist, @hemlock{} will ask if it should
be created.
@end deffn

@deffn {Command} {Netnews Message File Message} stuff (bound to @b{o} in @hid{News-Message} mode)
This command prompts for a mail folder and files the current message there.
If the folder does not exist, @hemlock{} will ask if it should be created.
@end deffn

@deffn {Command} {Fetch All Headers} stuff (bound to @b{f} in @hid{Netnews Headers} mode)
   In a forward reading @hid{Netnews headers} buffer, this command inserts
   all headers after the last visible one into the headers buffer.  If
   @hemlock{} is reading this group backward, the system inserts all headers
   before the first visible one into the headers buffer.
@end deffn

@deffn {Command} {Netnews Go to Next Group} stuff (bound to @b{g} in @hid{News-Headers} and @hid{News-Message} modes.)
This command goes to the next group in your @hid{Netnews Group File}.
Before going on, it sets the group pointer in @hid{Netnews Database
Filename} to the last message you read.  With an argument, the command does
not modify the group pointer for the current group.
@end deffn

@deffn {Command} {Netnews Quit Starting Here} stuff (bound to @b{.} in @hid{News-Headers} and @hid{News-Message} modes)
   This command goes to the next group in your @hid{Netnews Group File}, 
   setting the netnews pointer for this group to the message before the one
   under the current point, so the next time you read this group, the message
   indicated by the point will appear first.
@end deffn

@deffn {Command} {Netnews Group Punt Messages} stuff (bound to @b{G} in @hid{News-Headers} mode)
   This command goes on to the next bulletin board in your group
   file.  Without an argument, the system sets the pointer for the current
   group to the last message.  With an argument, @hemlock{} sets the
   pointer to the last visible message in the group.
@end deffn

@deffn {Command} {Netnews Exit} stuff (bound to @b{q} in @hid{News-Headers} mode)
@deffnx {Hemlock Variable} {Netnews Exit Confirm} @val{t}
   This command cleans up and deletes the @hid{News-Headers} buffer and
   all associated @hid{News-Message} buffers.  If the value of
   @hid{Netnews Exit Confirm} is @nil, then @hemlock{} will not prompt before
   exiting.
@end deffn

@node Replying to Messages, Posting Messages, Reading Newnews Messages, The Hemlock Netnews Interface
@section Replying to Messages

The @hemlock{} Netnews interface also provides an easy way of replying to
messages through the @hemlock{} Mailer or via @hid{Post} mode.

@deffn {Command} {Netnews Reply to Sender}
   When you invoke this command, @hemlock{} creates a @hid{Draft} buffer and
   tries to fill in the @i{to} and @i{subject} fields of the draft.  For
   the @i{to} field, @hemlock{} looks at the @i{reply-to} field of the
   message you are replying to, or failing that, the @i{from} field.  If
   the @i{subject} field does not start with @b{Re:}, @hemlock{} inserts this
   string, signifying that this is a reply.
@end deffn

@deffn {Command} {Netnews Reply to Sender in Other Window} stuff (bound to @b{r} in @hid{News-Headers} and @hid{News-Message}.)
This command splits the current window, placing the message you are
replying to in the top window and a new @hid{Draft} buffer in the bottom
one.  This command fills in the header fields in the same manner as
@hid{Netnews Reply to Sender}.
@end deffn

@deffn {Command} {Netnews Reply to Group}
This command creates a @hid{Post} buffer with the @i{newsgroups} field set
to the current group and the @i{subject} field constructed in the same way
as in @hid{Netnews Reply to Sender}.
@end deffn

@deffn {Command} {Netnews Reply to Group in Other Window} stuff (bound to @b{R} in @hid{News-Headers} and @hid{News-Message}.)
   This command splits the current window, placing the message you are
   replying to in the top window and a new @hid{Post} buffer in the bottom
   one.  This command will fill in the header fields in the same manner as
   @hid{Netnews Reply to Group}.
@end deffn

@deffn {Command} {Netnews Post Message} stuff (bound to @b{C-x P})
   This command creates a @hid{Post} buffer.  If you are in a 
   @hid{News-Headers} or @hid{News-Message} buffer, @hemlock{} fills in the
   @i{newsgroups} field with the current group.
@end deffn

@deffn {Command} {Netnews Forward Message} stuff (bound to @b{f} in @hid{News-Headers} and @hid{News-Message} modes.)
This command creates a @hid{Post} buffer.  If you are in a @hid{Netnews
Headers} or @hid{News-Message} buffer, @hemlock{} will put the text of the
current message into the buffer along with lines delimiting the forwarded
message.
@end deffn

@deffn {Command} {Netnews Goto Post Buffer} stuff (bound to @b{H-p} in @hid{News-Message} mode)
   This command, when invoked in a @hid{News-Message} or @hid{Draft} buffer
   with an associated @hid{News-Headers} buffer, places the associated
   @hid{News-Headers} buffer into the current window.
@end deffn

@deffn {Command} {Netnews Goto Draft Buffer} stuff (bound to @b{H-d} in @hid{News-Message} mode)
   This command, when invoked in a @hid{News-Message} buffer with an 
   associated @hid{Draft} buffer, places the @hid{Draft} buffer into the 
   current window.
@end deffn

@node Posting Messages, Netnews Wallchart, Replying to Messages, The Hemlock Netnews Interface
@section Posting Messages

@deffn {Command} {Netnews Deliver Post} stuff (bound to @b{H-s} in @hid{Post} mode)
@deffnx {Hemlock Variable} {Netnews Deliver Post Confirm} @val{t}
This command delivers the contents of a @hid{Post} buffer to the NNTP
server.  If @hid{Netnews Deliver Post Confirm} is @b{t}, @hemlock{} will ask for
confirmation before posting the message.  @hemlock{} feeps you if NNTP does
not accept the message.
@end deffn

@deffn {Command} {Netnews Abort Post} stuff (bound to @b{H-q} in @hid{Post} mode)
   This command deletes the current @hid{Post} buffer.
@end deffn


As in the mailer, when replying to a message you can be excerpt sections of
it using @hid{Insert Message Buffer} and @hid{Insert Message Region} in
@hid{Post} and @hid{News-Message} modes, respectively.  You can also use
these commands when replying to a message via mail in a @hid{Draft} buffer.
In all cases, the same binding is used: @b{H-y}.

@page
@node Netnews Wallchart,  , Posting Messages, The Hemlock Netnews Interface
@section Wallchart

@center @b{Global bindings:}
@multitable @columnfractions .7 .1 .2

@item @hid{Netnews Post Message} @tab  @tab @b{C-x P}
@end multitable

@sp 2
@center @b{News-Headers and News-Message modes bindings:}
@multitable @columnfractions .7 .1 .2

@item @hid{Netnews Next Article} @tab @tab @b{n}
@item @hid{Netnews Previous Article} @tab  @tab @b{p}
@item @hid{Netnews Go to Next Group} @tab  @tab @b{g}
@item @hid{Netnews Group Punt Messages} @tab  @tab @b{G}
@item @hid{List All Groups} @tab  @tab @b{l}
@item @hid{Netnews Append to File} @tab  @tab @b{a}
@item @hid{Netnews Forward Message} @tab  @tab @b{f}
@item @hid{Netnews Reply to Sender in Other Window} @tab  @tab @b{r}
@item @hid{Netnews Reply to Group in Other Window} @tab  @tab @b{R}
@item @hid{Netnews Quit Starting Here} @tab  @tab @b{.}
@end multitable

@sp 2
@center@b{News-Headers mode bindings:}

@multitable @columnfractions .7 .1 .2
@item @hid{Netnews Show Article} @tab  @tab @b{Space}
@item @hid{Netnews Previous Line} @tab  @tab @b{C-p}, @b{Uparrow}
@item @hid{Netnews Next Line} @tab  @tab  @b{C-n}, @b{Downarrow}
@item @hid{Netnews Headers Scroll Window Down} @tab  @tab @b{C-v}
@item @hid{Netnews Headers Scroll Window Up} @tab @tab @b{M-v}
@item @hid{Netnews Select Message Buffer} @tab  @tab @b{H-m}
@item @hid{Netnews Exit} @tab  @tab @b{q}
@item @hid{Netnews Headers File Message} @tab  @tab @b{o}
@end multitable

@center @b{News-Message mode bindings:}
@multitable @columnfractions .7 .1 .2

@item @hid{Netnews Message Scroll Down} @tab  @tab @b{Space}
@item @hid{Scroll Window Up} @tab  @tab @b{Backspace}
@item @hid{Netnews Goto Headers Buffer} @tab  @tab @b{H-h}, @b{^}
@item @hid{Netnews Message Keep Buffer} @tab  @tab @b{k}
@item @hid{Netnews Message Quit} @tab  @tab @b{q}
@item @hid{Netnews Message File Message} @tab  @tab @b{o}
@item @hid{Netnews Goto Post Buffer} @tab  @tab @b{H-p}
@item @hid{Netnews Goto Draft Buffer} @tab  @tab @b{H-d}
@item @hid{Insert Message Region} @tab  @tab @b{H-y}
@end multitable

@sp 2
@center @b{Post mode bindings:}

@multitable @columnfractions .7 .1 .2

@item @hid{Netnews Select Message Buffer} @tab  @tab @b{H-m}
@item @hid{Netnews Deliver Post} @tab  @tab @b{H-s}
@item @hid{Netnews Abort Post} @tab  @tab @b{H-q}
@item @hid{Insert Message Buffer} @tab  @tab @b{H-y}
@end multitable

@sp 2
@center @b{News-Browse mode bindings:}
@multitable @columnfractions .7 .1 .2

@item @hid{Netnews Quit Browse} @tab  @tab @b{q}
@item @hid{Netnews Browse Add Group To File} @tab  @tab @b{a}
@item @hid{Netnews Browse Read Group} @tab  @tab @b{Space}
@item @hid{Next Line} @tab  @tab   @b{n}
@item @hid{Previous Line} @tab  @tab  @b{p}

@end multitable
