s/@i\[\([^]]\+\)\]/@i{\1}/g
s/@f\[\([^]]\+\)\]/@b{\1}/g
s/@hid\[\([^]]\+\)\]/@hid{\1}/g
s/@var\[\([^]]\+\)\]/@var{\1}/g
s/@binding\[\([^]]\+\)\]/@binding{\1}/g
s/@ref\[\([^]]\+\)\]/@ref{\1}/g
s/@pageref\[\([^]]\+\)\]/@pageref{\1}/g
s/@bf\[\([^]]\+\)\]/@b{\1}/g
s/@kwd\[\([^]]\+\)\]/@kwd{\1}/g
s/@comref\[\([^]]\+\)\]/@comref{\1}/g
s/@hvarref<\([^]]\+\)>/@hvarref{\1}/g
s/^@comment/@c /
s/@chap\[\([^]]\+\)\]/@chapter \1/
s/@section\[\([^]]\+\)\]/@section \1/
s/@subsection\[\([^]]\+\)\]/@subsection \1/
s/^@defhvar\[var "\([^"]\+\)", val \([^]]\+\)\]/@defvr {Hemlock Variable} {\1} @val\2/
s/^@defhvar\[var "\([^"]\+\)"\]/@defvr {Hemlock Variable} {\1}/
s/^@defhvar1\[var "\([^"]\+\)", val \([^]]\+\)\]/@defvrx {Hemlock Variable} {\1} @val\2/
s/^@defhvar1\[var "\([^"]\+\)"\]/@defvrx {Hemlock Variable} {\1}/
s/^@enddefhvar$/@end defvr/
s/^@index\[\([^,]\+\), \([^]]\+\)\]/@cindex \1 @subentry \2/
s/^@index\[\([^]]\+\)\]/@cindex \1/
s/^@label\[\([^]]\+\)\]/@anchor{\1}/
s/^@begin\[programexample\]/@example/
s/^@end\[programexample\]/@end example/
s/^@defcom\[com "\([^"]\+\)", bind [({]\([^)]\+\)[)}]\]/@deffn {Command} {\1} @bind{\2}/
s/^@defcom\[com "\([^"]\+\)"\]/@deffn {Command} {\1}/
s/^@defcom1\[com "\([^"]\+\)", bind [({]\([^)]\+\)[)}]\]/@deffnx {Command} {\1} @bind{\2}/
s/^@defcom1\[com "\([^"]\+\)"\]/@deffnx {Command} {\1}/
s/^@enddefcom$/@end deffn/
s/^@begin\[itemize\]/@itemize/
s/^@end\[itemize\]/@end itemize/

