texinfo_set_from_init_file("EXTRA_HEAD",  q{<link rel="icon" href="/favicon.ico">
<!-- Select the theme to use for highlighting.  github looks pretty good for the examples
     in the manual -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/nnfx-light.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
<!-- and it's easy to individually load additional languages -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/lisp.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/languages/c.min.js">
</script>

<!--
<script>
  // Only try to highlight lisp and c/c++ languages.
  // The CSS selector is meant to handle texinfo @lisp, @example lisp, and @example c.
  hljs.configure({
      languages: ['lisp', 'c', 'cpp'],
      cssSelector: '.lisp-preformatted, .example.user-lisp .example-preformatted, .example.user-c .example-preformtatted',
  });
  hljs.highlightAll();
</script>
-->
}
);
