source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-sass-converter", "~> 2.0"
gem "csv"
gem "base64"
gem "webrick"

# em-websocket/eventmachine are only needed for --livereload.
# They require native compilation (ruby-dev headers) so we exclude them.
group :livereload do
  gem "em-websocket"
  gem "eventmachine"
end
