\input texinfo
@settitle CMUCL User's Manual

@fonttextsize 10

@macro cmucl {}
@sc{cmucl}
@end macro

@macro clisp {}
Common Lisp
@end macro

@macro llisp {}
Common Lisp
@end macro

@macro hemlock {}
Hemlock
@end macro

@macro python {}
Python
@end macro

@macro alien {}
Alien
@end macro

@macro hide {arg}
@end macro

@macro F {arg}
@code{\arg\}
@end macro

@macro credits {arg}
@center @b{\arg\}
@end macro

@macro dash {}
---
@end macro

@macro false {}
@code{nil}
@end macro

@macro nil {}
@code{nil}
@end macro

@macro true {}
@code{t}
@end macro

@macro kwd {keyword}
@code{:\keyword\}
@end macro

@macro cltl {}
@i{Common Lisp: The Language}
@end macro

@macro cltltwo {}
@i{Common Lisp: The Language II}
@end macro

@macro argtype {arg}
@var{\arg\}
@end macro

@macro lispchar {arg}
@code{#@backslashchar{}\arg\}
@end macro

@macro amprest {}
&rest
@end macro

@macro ampbody {}
&body
@end macro

@macro ampoptional {}
@code{&optional}
@end macro

@macro tindexed {arg}
@code{\arg\}
@end macro

@macro findexed {arg}
@code{\arg\}
@end macro

@macro vindexed {arg}
@code{\arg\}
@end macro

@macro funref {arg}
@code{\arg\}
@end macro

@macro args {arg}
\arg\
@end macro

@macro mopt {arg}
@{\arg\@}
@end macro

@rmacro mstar {arg}
@{\arg\@}*
@end rmacro

@macro mplus {arg}
@{\arg\@}+
@end macro

@macro mor {}
|
@end macro

@macro mgroup {arg}
@{@var{\arg\}@}
@end macro

@macro keys {arg}
&key \arg\
@end macro

@macro morekeys {arg}
\arg\
@end macro

@macro yetmorekeys {arg}
\arg\
@end macro

@macro varref {arg}
@code{\arg\}
@end macro

@macro macref {arg}
@code{\arg\}
@end macro

@macro manualdate {}
December 2018
@end macro

@macro manualvers {}
21d
@end macro

@macro manualauthor {}
Robert A. MacLachlan, @i{Editor}
@end macro

@macro shortdescription {}
@cmucl{} is a free, high-performance implementation of the Common Lisp
programming language, which runs on most major Unix platforms. It
mainly conforms to the ANSI Common Lisp Standard. @cmucl{} features a
sophisticated native-code compiler, a foreign function interface, a
graphical source-level debugger, an interface to the X11 Window
System, and an Emacs-like editor.
@end macro

@titlepage
@title CMUCL User's Manual
@subtitle @manualdate{}
@subtitle @manualvers{}
@author @manualauthor{}

@iftex
@vskip 10pt
@end iftex
@quotation
@shortdescription{}

@iftex
@vskip 5pt
@end iftex
@b{Keywords}: lisp, Common Lisp, manual, compiler, programming
language implementation, programming environment
@iftex
@vskip 5cm
@end iftex
This manual is based on CMU Technical Report CMU-CS-92-161, edited by
Robert A. MacLachlan, dated July 1992.
@end quotation

@end titlepage

@ifnottex
@shortcontents
@end ifnottex
@contents

@ifnottex
@node Top
@top

@b{CMUCL User's Manual} version @manualdate{}, @manualvers{}.

@noindent
@manualauthor{}

@shortdescription{}

@b{Keywords}: lisp, Common Lisp, manual, compiler, programming
language implementation, programming environment

This manual is based on CMU Technical Report CMU-CS-92-161, edited by
Robert A. MacLachlan, dated July 1992.

@menu
* Introduction::
* Design Choices and Extensions::
* The Debugger::
* The Compiler::
* Advanced Compiler Use and Efficiency Hints::
* UNIX Interface::
* Event Dispatching with SERVE-EVENT::
* Alien Objects::
* Interprocess Communication under LISP::
* Networking Support::
* Debugger Programmer's Interface::
* Cross-Referencing Facility::
* Internationalization::
* Function Index::
* Variable Index::
* Type Index::
* Concept Index::

@end menu

@end ifnottex

@include introduction.texi
@include extensions.texi
@include debugger.texi
@include compiler.texi
@include compiler-hint.texi
@include unix.texi
@include serve-event.texi
@include aliens.texi
@include ipc.texi
@include internet.texi
@include debug-internals.texi
@include cross-referencing.texi
@include unicode.texi

@node Function Index
@unnumbered Function Index
@printindex fn

@node Variable Index
@unnumbered Variable Index
@printindex vr

@node Type Index
@unnumbered Type Index
@printindex tp

@node Concept Index
@unnumbered Concept Index
@printindex cp

@bye
